# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

linter:
  rules:
     # Identifier
    - camel_case_types              # DO name types using UpperCamelCase
    - camel_case_extensions         # DO name extensions using UpperCamelCase
    - file_names                    # DO name packages, directories, and source files using lowercase_with_underscores
    - package_names
    - library_prefixes              # DO name import prefixes using lowercase_with_underscores
    - non_constant_identifier_names # DO name other identifiers using lowerCamelCase
    - constant_identifier_names     # PREFER using lowerCamelCase for constant names
    - no_wildcard_variable_uses     # DON'T use wildcard parameters or variables.
    - unnecessary_underscores       # AVOID using multiple underscores when a single wildcard will do.
    - directives_ordering           # DO place dart: > package: > alphabetically > specify exports
    # DO format your code using `dart format`
    - lines_longer_than_80_chars    # AVOID lines longer than 80 characters
    - curly_braces_in_flow_control_structures # DO use curly braces for all flow control statements
    # Doc comments are especially handy because `dart doc` parses them and generates doc pages
    - slash_for_doc_comments
    - comment_references            # DO reference only in-scope identifiers in doc comments.
    # Usage
    - use_string_in_part_of_directives # DO use strings in `part of` directives
    - implementation_imports        # DON'T import libraries that are inside the `src` directory of another package
    - avoid_relative_lib_imports    # DON'T allow an import path to reach into or out of `lib`
    - prefer_relative_imports       # PREFER relative import paths
    - avoid_init_to_null            # DON'T explicitly initialize variables to `null`, or use as default value
    - prefer_adjacent_string_concatenation # DO use adjacent strings to concatenate string literals
    - prefer_interpolation_to_compose_strings # PREFER using interpolation to compose strings and values
    - unnecessary_brace_in_string_interps # AVOID using curly braces in interpolation when not needed
    - prefer_collection_literals    # DO use collection literals when possible
    - prefer_is_empty               # DON'T use `.length` to see if a collection is empty
    - prefer_is_not_empty
    - avoid_function_literals_in_foreach_calls # AVOID using `Iterable.forEach()` with a function literal
    - prefer_iterable_whereType     # DO use `whereType()` to filter a collection by type
    - prefer_function_declarations_over_variables # DO use a function declaration to bind a function to a name
    - unnecessary_lambdas           # DON'T create a lambda when a tear-off will do
    - unnecessary_getters_setters   # DON'T wrap a field in a getter and setter unnecessarily
    - prefer_expression_function_bodies # CONSIDER using `=>` for simple members
    - unnecessary_this              # DON'T use `this.` except to redirect to a named constructor or to avoid shadowing
    - prefer_initializing_formals   # DO use initializing formals when possible
    - empty_constructor_bodies      # DO use `;` instead of `{}` for empty constructor bodies
    - unnecessary_new               # DON'T use `new`
    - unnecessary_const             # DON'T use `const` redundantly

analyzer:
  strong-mode:
    implicit-casts: false    # 禁止隐式类型转换（如 dynamic → int）
    implicit-dynamic: false  # 禁止隐式 dynamic 类型
  language:
    strict-raw-types: true   # 强制泛型类型明确
  errors:
    missing_return: error    # 函数缺少返回值报错
    unused_element: warning  # 未使用的元素警告
  exclude:
    - "build/**"          # 忽略构建目录
    - "lib/generated/**"  # 忽略代码生成文件

